// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: streaming_service.proto

package filepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_streaming_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadFileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stream []byte `protobuf:"bytes,1,opt,name=Stream,proto3" json:"Stream,omitempty"`
}

func (x *ReadFileReply) Reset() {
	*x = ReadFileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileReply) ProtoMessage() {}

func (x *ReadFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileReply.ProtoReflect.Descriptor instead.
func (*ReadFileReply) Descriptor() ([]byte, []int) {
	return file_streaming_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReadFileReply) GetStream() []byte {
	if x != nil {
		return x.Stream
	}
	return nil
}

type LsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir string `protobuf:"bytes,1,opt,name=Dir,proto3" json:"Dir,omitempty"`
}

func (x *LsRequest) Reset() {
	*x = LsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsRequest) ProtoMessage() {}

func (x *LsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsRequest.ProtoReflect.Descriptor instead.
func (*LsRequest) Descriptor() ([]byte, []int) {
	return file_streaming_service_proto_rawDescGZIP(), []int{2}
}

func (x *LsRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type LsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []string `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
}

func (x *LsReply) Reset() {
	*x = LsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsReply) ProtoMessage() {}

func (x *LsReply) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsReply.ProtoReflect.Descriptor instead.
func (*LsReply) Descriptor() ([]byte, []int) {
	return file_streaming_service_proto_rawDescGZIP(), []int{3}
}

func (x *LsReply) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type MetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *MetaRequest) Reset() {
	*x = MetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRequest) ProtoMessage() {}

func (x *MetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRequest.ProtoReflect.Descriptor instead.
func (*MetaRequest) Descriptor() ([]byte, []int) {
	return file_streaming_service_proto_rawDescGZIP(), []int{4}
}

func (x *MetaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MetaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size  int64  `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"` // in bytes
	Mode  uint32 `protobuf:"varint,2,opt,name=Mode,proto3" json:"Mode,omitempty"` // rwxrwxrwx bit array, 31-9 bits not used
	IsDir bool   `protobuf:"varint,3,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
}

func (x *MetaReply) Reset() {
	*x = MetaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaReply) ProtoMessage() {}

func (x *MetaReply) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaReply.ProtoReflect.Descriptor instead.
func (*MetaReply) Descriptor() ([]byte, []int) {
	return file_streaming_service_proto_rawDescGZIP(), []int{5}
}

func (x *MetaReply) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetaReply) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MetaReply) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

var File_streaming_service_proto protoreflect.FileDescriptor

var file_streaming_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22,
	0x25, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22,
	0x1d, 0x0a, 0x09, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x69, 0x72, 0x22, 0x1f,
	0x0a, 0x07, 0x4c, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22,
	0x21, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x4f, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49, 0x73, 0x44, 0x69, 0x72, 0x4a, 0x04, 0x08,
	0x04, 0x10, 0x09, 0x32, 0x9f, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x15, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12,
	0x26, 0x0a, 0x02, 0x4c, 0x73, 0x12, 0x0f, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x4c, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x4c, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x11, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_streaming_service_proto_rawDescOnce sync.Once
	file_streaming_service_proto_rawDescData = file_streaming_service_proto_rawDesc
)

func file_streaming_service_proto_rawDescGZIP() []byte {
	file_streaming_service_proto_rawDescOnce.Do(func() {
		file_streaming_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_streaming_service_proto_rawDescData)
	})
	return file_streaming_service_proto_rawDescData
}

var file_streaming_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_streaming_service_proto_goTypes = []interface{}{
	(*ReadFileRequest)(nil), // 0: file.ReadFileRequest
	(*ReadFileReply)(nil),   // 1: file.ReadFileReply
	(*LsRequest)(nil),       // 2: file.LsRequest
	(*LsReply)(nil),         // 3: file.LsReply
	(*MetaRequest)(nil),     // 4: file.MetaRequest
	(*MetaReply)(nil),       // 5: file.MetaReply
}
var file_streaming_service_proto_depIdxs = []int32{
	0, // 0: file.FileService.ReadFile:input_type -> file.ReadFileRequest
	2, // 1: file.FileService.Ls:input_type -> file.LsRequest
	4, // 2: file.FileService.Meta:input_type -> file.MetaRequest
	1, // 3: file.FileService.ReadFile:output_type -> file.ReadFileReply
	3, // 4: file.FileService.Ls:output_type -> file.LsReply
	5, // 5: file.FileService.Meta:output_type -> file.MetaReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streaming_service_proto_init() }
func file_streaming_service_proto_init() {
	if File_streaming_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_streaming_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streaming_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadFileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streaming_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streaming_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streaming_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streaming_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_streaming_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_service_proto_goTypes,
		DependencyIndexes: file_streaming_service_proto_depIdxs,
		MessageInfos:      file_streaming_service_proto_msgTypes,
	}.Build()
	File_streaming_service_proto = out.File
	file_streaming_service_proto_rawDesc = nil
	file_streaming_service_proto_goTypes = nil
	file_streaming_service_proto_depIdxs = nil
}
